{"failedTests":[{"testName":"benchmark/test-benchmark-crypto","timestamp":1752401909120,"status":"FAILED","jobName":"node-test-binary-windows-native-suites","config":"node-test-binary-windows-native-suites Â» win2022-vs2022-COMPILED_BY-vs2022 #28808","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-native-suites/nodes=win2022-vs2022-COMPILED_BY-vs2022/28808/","buildNumber":28808,"builtOn":"test-rackspace-win2022_vs2022-x64-6","nodeVersion":"22.17.1","commitHash":"4af591517732beb194293386ad31dc9c55f10fb7","callStack":[{"upstreamBuild":71614,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":81207,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":264,"upstreamProject":"node-daily-v22.x-staging","upstreamUrl":"job/node-daily-v22.x-staging/"}],"tap":{"ok":false,"name":"benchmark/test-benchmark-crypto","id":182,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"node:assert:95\n  throw new AssertionError(obj);\n  ^\n\nAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\n1 !== 0\n\n    at main (C:\\workspace\\node-test-binary-windows-native-suites\\node\\benchmark\\crypto\\timingSafeEqual.js:21:10)\n    at C:\\workspace\\node-test-binary-windows-native-suites\\node\\benchmark\\common.js:63:9\n    at process.processTicksAndRejections (node:internal/process/task_queues:85:11) {\n  generatedMessage: true,\n  code: 'ERR_ASSERTION',\n  actual: 1,\n  expected: 0,\n  operator: 'strictEqual'\n}\n\nNode.js v22.17.1-pre\nnode:internal/process/promises:392\n      new UnhandledPromiseRejection(reason);\n      ^\n\nUnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason \"1\".\n    at throwUnhandledRejectionsMode (node:internal/process/promises:392:7)\n    at processPromiseRejections (node:internal/process/promises:475:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:106:32) {\n  code: 'ERR_UNHANDLED_REJECTION'\n}\n\nNode.js v22.17.1-pre\nnode:assert:95\n  throw new AssertionError(obj);\n  ^\n\nAssertionError [ERR_ASSERTION]: Expected values to be strictly equal:\n\n1 !== 0\n\n    at ChildProcess.<anonymous> (C:\\workspace\\node-test-binary-windows-native-suites\\node\\test\\common\\benchmark.js:28:12)\n    at ChildProcess.emit (node:events:518:28)\n    at ChildProcess._handle.onexit (node:internal/child_process:293:12) {\n  generatedMessage: true,\n  code: 'ERR_ASSERTION',\n  actual: 1,\n  expected: 0,\n  operator: 'strictEqual'\n}\n\nNode.js v22.17.1-pre"},"time":6412.062,"fullname":"benchmark/test-benchmark-crypto","closingTestPoint":false}}]}