{"failedTests":[{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 3,win10-COMPILED_BY-vs2022 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022/27841/","buildNumber":27841,"builtOn":"test-azure_msft-win10_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":637,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 236.3208\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 214.2721\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 133.7413\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 125.6434\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 124.3375\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 120.8236\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 168.6553\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 112.282\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 144.6434\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 166.3728\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 144.0293\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 127.0681\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 144.1971\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 125.0847\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 122.6484\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 141.3253\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 115.585\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 142.8593\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 137.5234\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 130.9505\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 135.4226\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 136.0687\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 126.9518\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 143.3835\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 136.2159\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 129.7992\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 150.6245\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 95.1402\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 3935.9214\n  type: 'suite'\n  location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 3944.9805"},"time":4256.017,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 3,win2016-COMPILED_BY-vs2022-x86 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2016-COMPILED_BY-vs2022-x86/27841/","buildNumber":27841,"builtOn":"test-azure_msft-win2016_vs2017-x64-2","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":630,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 220.664\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 172.3266\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 102.2911\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 121.0678\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 102.3099\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 106.5968\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 155.9588\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 100.6945\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 111.6739\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 106.5888\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 111.2499\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 119.1451\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 96.4996\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 116.6249\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 99.628\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 100.6879\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 111.749\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 128.7555\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 113.6234\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 110.7852\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 105.2966\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 99.9473\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 121.0602\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 120.8958\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 106.1734\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 103.5201\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 121.0354\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 84.9808\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 3276.5975\n  type: 'suite'\n  location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 3297.1487"},"time":3594.046,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 3,win2019-COMPILED_BY-vs2022 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2019-COMPILED_BY-vs2022/27841/","buildNumber":27841,"builtOn":"test-rackspace-win2019_vs2019-x64-3","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":671,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 314.5971\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 278.562\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 165.4757\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 170.165\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 199.9119\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 172.7559\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 234.3516\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 163.2901\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 165.0818\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 164.5267\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 158.5198\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 190.6971\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 159.0843\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 160.7456\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 163.6089\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 169.0472\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 158.156\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 156.3331\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 156.463\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 166.0933\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 220.2416\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 156.7559\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 158.0098\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 190.2859\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 309.5678\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 165.2333\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 164.1625\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 108.6782\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 5148.7376\n  type: 'suite'\n  location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 5167.5441"},"time":5599.04,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 3,win11-COMPILED_BY-vs2022 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-COMPILED_BY-vs2022/27841/","buildNumber":27841,"builtOn":"test-azure_msft-win11_vs2022-x64-2","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":636,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 228.0135\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 206.0216\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 108.7427\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 132.1708\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 109.1504\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 126.9183\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 174.6511\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 103.0851\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 129.8763\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 126.0929\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 165.4114\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 115.2876\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 102.5422\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 118.1492\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 135.8214\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 114.6252\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 118.8057\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 120.1474\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 160.4986\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 115.4898\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 109.9308\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 125.573\n      location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (c:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///c:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 185.2866\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 149.0826\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 114.3982\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 125.6768\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 129.3351\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 96.8417\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 3751.8992\n  type: 'suite'\n  location: 'c:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 3761.3538"},"time":4197.059,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 3,win2022-COMPILED_BY-vs2022 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win2022-COMPILED_BY-vs2022/27841/","buildNumber":27841,"builtOn":"test-rackspace-win2022_vs2022-x64-2","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":676,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 335.0914\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 291.8221\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 230.9189\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 222.3307\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 251.0649\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 193.3872\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 262.4185\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 189.264\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 207.967\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 212.8009\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 196.8095\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 222.1367\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 184.3366\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 179.8532\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 192.0681\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 205.4136\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 194.2986\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 183.1894\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 187.3873\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 190.044\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 185.022\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 217.801\n      location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (C:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 349.0184\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 197.4409\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 196.6559\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 194.001\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 202.8682\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 144.782\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 6028.2712\n  type: 'suite'\n  location: 'C:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 6047.845"},"time":6506.083,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-node-output-errors","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 0,win11-arm64-COMPILED_BY-vs2022-arm64 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022-arm64/27841/","buildNumber":27841,"builtOn":"test-azure_msft-win11_vs2022-arm64-6","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-node-output-errors","id":677,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"TAP version 13\n# Subtest: errors output\n    # Subtest: errors/async_error_eval_cjs.js\n    ok 1 - errors/async_error_eval_cjs.js\n      ---\n      duration_ms: 382.4724\n      ...\n    # Subtest: errors/async_error_eval_esm.js\n    ok 2 - errors/async_error_eval_esm.js\n      ---\n      duration_ms: 398.5827\n      ...\n    # Subtest: errors/async_error_microtask_main.js\n    ok 3 - errors/async_error_microtask_main.js\n      ---\n      duration_ms: 272.7433\n      ...\n    # Subtest: errors/async_error_nexttick_main.js\n    ok 4 - errors/async_error_nexttick_main.js\n      ---\n      duration_ms: 248.7818\n      ...\n    # Subtest: errors/async_error_sync_main.js\n    ok 5 - errors/async_error_sync_main.js\n      ---\n      duration_ms: 245.6548\n      ...\n    # Subtest: errors/core_line_numbers.js\n    ok 6 - errors/core_line_numbers.js\n      ---\n      duration_ms: 224.6423\n      ...\n    # Subtest: errors/async_error_sync_esm.mjs\n    ok 7 - errors/async_error_sync_esm.mjs\n      ---\n      duration_ms: 323.7172\n      ...\n    # Subtest: errors/test-no-extra-info-on-fatal-exception.js\n    ok 8 - errors/test-no-extra-info-on-fatal-exception.js\n      ---\n      duration_ms: 231.2462\n      ...\n    # Subtest: errors/error_aggregateTwoErrors.js\n    ok 9 - errors/error_aggregateTwoErrors.js\n      ---\n      duration_ms: 247.7284\n      ...\n    # Subtest: errors/error_exit.js\n    ok 10 - errors/error_exit.js\n      ---\n      duration_ms: 270.8313\n      ...\n    # Subtest: errors/error_with_nul.js\n    ok 11 - errors/error_with_nul.js\n      ---\n      duration_ms: 218.3342\n      ...\n    # Subtest: errors/events_unhandled_error_common_trace.js\n    ok 12 - errors/events_unhandled_error_common_trace.js\n      ---\n      duration_ms: 249.0504\n      ...\n    # Subtest: errors/events_unhandled_error_nexttick.js\n    ok 13 - errors/events_unhandled_error_nexttick.js\n      ---\n      duration_ms: 206.3882\n      ...\n    # Subtest: errors/events_unhandled_error_sameline.js\n    ok 14 - errors/events_unhandled_error_sameline.js\n      ---\n      duration_ms: 221.6238\n      ...\n    # Subtest: errors/events_unhandled_error_subclass.js\n    ok 15 - errors/events_unhandled_error_subclass.js\n      ---\n      duration_ms: 210.9489\n      ...\n    # Subtest: errors/if-error-has-good-stack.js\n    ok 16 - errors/if-error-has-good-stack.js\n      ---\n      duration_ms: 239.5263\n      ...\n    # Subtest: errors/throw_custom_error.js\n    ok 17 - errors/throw_custom_error.js\n      ---\n      duration_ms: 216.4607\n      ...\n    # Subtest: errors/throw_error_with_getter_throw.js\n    not ok 18 - errors/throw_error_with_getter_throw.js\n      ---\n      duration_ms: 207.8239\n      location: 'd:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_error_with_getter_throw.js:*\\n' +\n            'throw {  * eslint-disable-line no-throw-literal\\n' +\n            '^\\n' +\n            '[object Object]\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_error_with_getter_throw.js:*\n        throw {  * eslint-disable-line no-throw-literal\n        ^\n        [object Object]\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///d:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_in_line_with_tabs.js\n    ok 19 - errors/throw_in_line_with_tabs.js\n      ---\n      duration_ms: 232.8635\n      ...\n    # Subtest: errors/throw_non_error.js\n    ok 20 - errors/throw_non_error.js\n      ---\n      duration_ms: 295.4895\n      ...\n    # Subtest: errors/throw_null.js\n    not ok 21 - errors/throw_null.js\n      ---\n      duration_ms: 237.2378\n      location: 'd:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_null.js:*\\n' +\n            'throw null;\\n' +\n            '^\\n' +\n            'null\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_null.js:*\n        throw null;\n        ^\n        null\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///d:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/throw_undefined.js\n    not ok 22 - errors/throw_undefined.js\n      ---\n      duration_ms: 222.0907\n      location: 'd:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:78:5'\n      failureType: 'testCodeFailure'\n      error: |-\n        Expected values to be strictly equal:\n        + actual - expected\n        \n          '\\n' +\n            '*throw_undefined.js:*\\n' +\n            'throw undefined;\\n' +\n            '^\\n' +\n            'undefined\\n' +\n        +   '(Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\\n' +\n        -   '(Use `node --trace-uncaught ...` to show where the exception was thrown)\\n' +\n            '\\n' +\n            'Node.js *\\n'\n      code: 'ERR_ASSERTION'\n      name: 'AssertionError'\n      expected: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      actual: |-\n        \n        *throw_undefined.js:*\n        throw undefined;\n        ^\n        undefined\n        (Use `node.exe --trace-uncaught ...` to show where the exception was thrown)\n        \n        Node.js *\n        \n      operator: 'strictEqual'\n      stack: |-\n        assertSnapshot (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:56:12)\n        async Module.spawnAndAssert (d:\\workspace\\node-test-binary-windows-js-suites\\node\\test\\common\\assertSnapshot.js:84:3)\n        async TestContext.<anonymous> (file:///d:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-node-output-errors.mjs:79:7)\n        async Test.run (node:internal/test_runner/test:825:9)\n        async Suite.processPendingSubtests (node:internal/test_runner/test:533:7)\n      ...\n    # Subtest: errors/timeout_throw.js\n    ok 23 - errors/timeout_throw.js\n      ---\n      duration_ms: 227.5941\n      ...\n    # Subtest: errors/undefined_reference_in_new_context.js\n    ok 24 - errors/undefined_reference_in_new_context.js\n      ---\n      duration_ms: 232.8398\n      ...\n    # Subtest: errors/promise_always_throw_unhandled.js\n    ok 25 - errors/promise_always_throw_unhandled.js\n      ---\n      duration_ms: 211.9717\n      ...\n    # Subtest: errors/promise_unhandled_warn_with_error.js\n    ok 26 - errors/promise_unhandled_warn_with_error.js\n      ---\n      duration_ms: 215.5152\n      ...\n    # Subtest: errors/unhandled_promise_trace_warnings.js\n    ok 27 - errors/unhandled_promise_trace_warnings.js\n      ---\n      duration_ms: 215.0022\n      ...\n    # Subtest: errors/force_colors.js\n    ok 28 - errors/force_colors.js\n      ---\n      duration_ms: 172.036\n      ...\n    1..28\nnot ok 1 - errors output\n  ---\n  duration_ms: 6883.8325\n  type: 'suite'\n  location: 'd:\\\\workspace\\\\node-test-binary-windows-js-suites\\\\node\\\\test\\\\parallel\\\\test-node-output-errors.mjs:23:1'\n  failureType: 'subtestsFailed'\n  error: '3 subtests failed'\n  code: 'ERR_TEST_FAILURE'\n  ...\n1..1\n# tests 28\n# suites 1\n# pass 25\n# fail 3\n# cancelled 0\n# skipped 0\n# todo 0\n# duration_ms 6895.6073"},"time":7371.003,"fullname":"parallel/test-node-output-errors","closingTestPoint":false}},{"testName":"parallel/test-error-serdes","timestamp":1716230948228,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites Â» 0,win10-COMPILED_BY-vs2022 #27841","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022/27841/","buildNumber":27841,"builtOn":"test-azure_msft-win10_vs2019-x64-3","nodeVersion":"23.0.0","commitHash":"a72c0c3e137a3886467b68866b0a9bc68589459e","callStack":[{"upstreamBuild":63107,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":70946,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":59321,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"53062"}],"tap":{"ok":false,"name":"parallel/test-error-serdes","id":944,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":120262.341,"fullname":"parallel/test-error-serdes","closingTestPoint":false}}]}