{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725653450332,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30039","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30039/","buildNumber":30039,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"d07b43371cebd1673c11b9576fbf004b59cbb8ed","callStack":[{"upstreamBuild":65623,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74082,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62071,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54771"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":111,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (6090.2269ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (6446.8512ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (6737.2039ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (6415.5883ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5871.6439ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (6633.578ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (6344.3193ms)\n  ✖ async-hooks\\test-async-local-storage-gcable.js (6909.4454ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 7)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (6509.9546ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (6674.5736ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (6327.2981ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (6896.6965ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (7229.468ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (6565.2594ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (6919.1715ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5912.3293ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (6799.6112ms)\n  ✔ parallel\\test-async-local-storage-bind.js (6257.3414ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (6077.6355ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (6400.4735ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (6878.141ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (6515.6404ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (6369.8338ms)\n▶ AsyncContextFrame (7849.4205ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 7867.8287\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-gcable.js (6909.4454ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 7)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":8450.538,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-async-context-frame","timestamp":1725653450332,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30039","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30039/","buildNumber":30039,"builtOn":"test-rackspace-win2022_vs2022-x64-5","nodeVersion":"23.0.0","commitHash":"d07b43371cebd1673c11b9576fbf004b59cbb8ed","callStack":[{"upstreamBuild":65623,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74082,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62071,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54771"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":106,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (4461.2465ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (5284.0694ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (4544.7394ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (5262.508ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5022.2152ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (4801.6214ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5068.8331ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (4625.3515ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (4867.1483ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (4845.3765ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (4836.1862ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (4923.1822ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5174.9255ms)\n  ✖ async-hooks\\test-async-local-storage-promises.js (4977.0474ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-promises.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 13)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-socket.js (4782.8364ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (4908.3127ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (4854.1331ms)\n  ✔ parallel\\test-async-local-storage-bind.js (4329.1577ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (4348.5713ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (4909.475ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (4544.123ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (4803.2572ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (4912.064ms)\n▶ AsyncContextFrame (5399.5722ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 5416.435\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-promises.js (4977.0474ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-promises.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 13)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":5959.226,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}},{"testName":"parallel/test-worker-arraybuffer-zerofill","timestamp":1725653450332,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 1,win2019-COMPILED_BY-vs2022 #30039","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win2019-COMPILED_BY-vs2022/30039/","buildNumber":30039,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"d07b43371cebd1673c11b9576fbf004b59cbb8ed","callStack":[{"upstreamBuild":65623,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74082,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62071,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54771"}],"tap":{"ok":false,"name":"parallel/test-worker-arraybuffer-zerofill","id":999,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"timeout"},"time":120267.202,"fullname":"parallel/test-worker-arraybuffer-zerofill","closingTestPoint":false}}]}