{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1725638732809,"status":"REGRESSION","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30030","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30030/","buildNumber":30030,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"b77476d8842d496bf27e5cea379e0bfcbc3acbb9","callStack":[{"upstreamBuild":65615,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74069,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":109,"buffered":false,"tapError":null,"skip":false,"todo":false,"previous":null,"plan":null,"diag":{"severity":"fail","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (5477.3084ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (5468.3557ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (6146.4404ms)\n  ✖ async-hooks\\test-async-local-storage-dgram.js (5146.5482ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-dgram.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:888:9)\n        at async Promise.all (index 3)\n        at async Suite.run (node:internal/test_runner/test:1268:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (5304.8523ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (5748.4407ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (5467.444ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (5594.7582ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (5976.0934ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (5784.3057ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (5690.0594ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (5135.3789ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (5354.7757ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (5721.2671ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (5717.218ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (5547.2798ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (5563.4876ms)\n  ✔ parallel\\test-async-local-storage-bind.js (5814.517ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (5852.2435ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (5712.2573ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (5277.2828ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (6003.0299ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (6001.0296ms)\n▶ AsyncContextFrame (7001.3405ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 7024.281\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:48:5\n✖ async-hooks\\test-async-local-storage-dgram.js (5146.5482ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-dgram.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:58:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:888:9)\n      at async Promise.all (index 3)\n      at async Suite.run (node:internal/test_runner/test:1268:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:280:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":7603.63,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}