{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1726504436617,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30296","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30296/","buildNumber":30296,"builtOn":"test-rackspace-win2019_vs2019-x64-4","nodeVersion":"23.0.0","commitHash":"cd32a660115a8b0d56f9fbb5e73cbb2bba296391","callStack":[{"upstreamBuild":65972,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74492,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62478,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54826"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":458,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1547.0759ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (2093.2407ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (2270.4723ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1670.6931ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1405.0216ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1760.8649ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1523.0365ms)\n  ✖ async-hooks\\test-async-local-storage-gcable.js (1500.4164ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:931:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1840.1454ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1716.3291ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1390.8185ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1673.7443ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1760.7109ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1247.0702ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1332.3583ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1301.0847ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1389.0268ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1203.2889ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1246.3519ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1254.4285ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1188.0182ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1490.7694ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1320.9197ms)\n▶ AsyncContextFrame (35151.1077ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 35169.2316\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-gcable.js (1500.4164ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-gcable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:931:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":35672.491,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}