{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1726642894907,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2019-COMPILED_BY-vs2022 #30331","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022/30331/","buildNumber":30331,"builtOn":"test-rackspace-win2019_vs2019-x64-2","nodeVersion":"23.0.0","commitHash":"c64f32ea23ae7814c2e5ed21707f3494b80ffe0b","callStack":[{"upstreamBuild":66009,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74533,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62516,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"54529"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":452,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✖ async-hooks\\test-async-local-storage-args.js (1488.4463ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-args.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:931:9)\n        at async Promise.all (index 0)\n        at async Suite.run (node:internal/test_runner/test:1295:7)\n        at async startSubtestAfterBootstrap (node:internal/test_runner/harness:289:3) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1588.3326ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1769.1644ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1488.0849ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1172.9255ms)\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1634.8285ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1424.6191ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1516.3833ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1466.4688ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1584.3094ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1352.6361ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1278.6061ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1527.6771ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1096.5875ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1135.1671ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1134.3831ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1243.2294ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1145.0638ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1124.015ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1183.1046ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1145.7373ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1434.369ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1128.9658ms)\n▶ AsyncContextFrame (31080.9174ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 31096.3538\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-args.js (1488.4463ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-args.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:931:9)\n      at async Promise.all (index 0)\n      at async Suite.run (node:internal/test_runner/test:1295:7)\n      at async startSubtestAfterBootstrap (node:internal/test_runner/harness:289:3) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":31499.626,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}