{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1727056106239,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30455","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30455/","buildNumber":30455,"builtOn":"test-rackspace-win2022_vs2022-x64-3","nodeVersion":"23.0.0","commitHash":"d59d7791e15c5dec9211be8ab1a0522e75ecd04c","callStack":[{"upstreamBuild":66146,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":74711,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":62677,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55025"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":432,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1326.5496ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1739.2111ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1708.6955ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1834.5816ms)\n  ✖ async-hooks\\test-async-local-storage-enable-disable.js (1445.7875ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:931:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-enter-with.js (1232.676ms)\n  ✔ async-hooks\\test-async-local-storage-errors.js (1250.6864ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1452.0149ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1319.2463ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1276.4336ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1234.3228ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1376.5225ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1621.6251ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1207.3504ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1257.4431ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1103.3118ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1344.2307ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1126.5764ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1167.4491ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1155.9726ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1093.9068ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1487.6754ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1161.323ms)\n✖ AsyncContextFrame (30940.8966ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 30954.7897\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enable-disable.js (1445.7875ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enable-disable.js failed with exit code 3221225477\n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:931:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:629:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":31342.054,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}