{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1728374206058,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 0,win2022-COMPILED_BY-vs2022 #30733","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022/30733/","buildNumber":30733,"builtOn":"test-rackspace-win2022_vs2022-x64-6","nodeVersion":"23.0.0","commitHash":"8dbca2d35b4b322320113e6a4a5ad752b1a84e6f","callStack":[{"upstreamBuild":66429,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":75065,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":3559,"upstreamProject":"node-daily-master","upstreamUrl":"job/node-daily-master/"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":488,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1559.3653ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1936.2182ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1762.0528ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (1725.3746ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1252.5366ms)\n  ✖ async-hooks\\test-async-local-storage-enter-with.js (1407.6478ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-errors.js (1671.4139ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1298.6217ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1286.652ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1335.3405ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1321.8455ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1324.7917ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1617.755ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1215.2493ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1087.4754ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1050.8489ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1231.4112ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1110.6551ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1078.8634ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1093.0662ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1134.6013ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1542.0148ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1275.6609ms)\n✖ AsyncContextFrame (31336.1644ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 31351.5144\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enter-with.js (1407.6478ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":31868.339,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}