{"failedTests":[{"testName":"parallel/test-async-context-frame","timestamp":1729392132410,"status":"FAILED","jobName":"node-test-binary-windows-js-suites","config":"node-test-binary-windows-js-suites » 2,win2022-COMPILED_BY-vs2022 #30930","buildUrl":"https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022/30930/","buildNumber":30930,"builtOn":"test-rackspace-win2022_vs2022-x64-3","nodeVersion":"24.0.0","commitHash":"bddf789a909de5a97efe8c1a19931e1dfe2bb350","callStack":[{"upstreamBuild":66633,"upstreamProject":"node-test-commit-windows-fanned","upstreamUrl":"job/node-test-commit-windows-fanned/"},{"upstreamBuild":75336,"upstreamProject":"node-test-commit","upstreamUrl":"job/node-test-commit/"},{"upstreamBuild":63208,"upstreamProject":"node-test-pull-request","upstreamUrl":"job/node-test-pull-request/"},{"prId":"55467"}],"tap":{"ok":false,"name":"parallel/test-async-context-frame","id":422,"buffered":false,"tapError":null,"skip":false,"todo":": Fix flaky test","previous":null,"plan":null,"diag":{"severity":"flaky","exitcode":1,"stack":"▶ AsyncContextFrame\n  ✔ async-hooks\\test-async-local-storage-args.js (1384.9246ms)\n  ✔ async-hooks\\test-async-local-storage-async-await.js (1636.4637ms)\n  ✔ async-hooks\\test-async-local-storage-async-functions.js (1386.0664ms)\n  ✔ async-hooks\\test-async-local-storage-dgram.js (2528.7626ms)\n  ✔ async-hooks\\test-async-local-storage-enable-disable.js (1586.2131ms)\n  ✖ async-hooks\\test-async-local-storage-enter-with.js (1634.0662ms)\n    AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n    \n    3221225477 !== 0\n    \n        at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n        at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n        at async Test.run (node:internal/test_runner/test:935:9)\n        at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n      generatedMessage: false,\n      code: 'ERR_ASSERTION',\n      actual: 3221225477,\n      expected: 0,\n      operator: 'strictEqual'\n    }\n\n  ✔ async-hooks\\test-async-local-storage-errors.js (1331.9867ms)\n  ✔ async-hooks\\test-async-local-storage-gcable.js (1451.0956ms)\n  ✔ async-hooks\\test-async-local-storage-http-agent.js (1218.6449ms)\n  ✔ async-hooks\\test-async-local-storage-http.js (1319.0544ms)\n  ✔ async-hooks\\test-async-local-storage-misc-stores.js (1310.6494ms)\n  ✔ async-hooks\\test-async-local-storage-nested.js (1244.8561ms)\n  ✔ async-hooks\\test-async-local-storage-no-mix-contexts.js (1695.9521ms)\n  ✔ async-hooks\\test-async-local-storage-promises.js (1267.0286ms)\n  ✔ async-hooks\\test-async-local-storage-socket.js (1270.9395ms)\n  ✔ async-hooks\\test-async-local-storage-thenable.js (1103.9668ms)\n  ✔ async-hooks\\test-async-local-storage-tlssocket.js (1352.1361ms)\n  ✔ parallel\\test-async-local-storage-bind.js (1122.6273ms)\n  ✔ parallel\\test-async-local-storage-contexts.js (1141.5429ms)\n  ✔ parallel\\test-async-local-storage-deep-stack.js (1120.2475ms)\n  ✔ parallel\\test-async-local-storage-exit-does-not-leak.js (1128.5937ms)\n  ✔ parallel\\test-async-local-storage-http-multiclients.js (1492.8741ms)\n  ✔ parallel\\test-async-local-storage-snapshot.js (1144.4534ms)\n✖ AsyncContextFrame (31888.9988ms)\nℹ tests 23\nℹ suites 1\nℹ pass 22\nℹ fail 1\nℹ cancelled 0\nℹ skipped 0\nℹ todo 0\nℹ duration_ms 31906.7256\n\n✖ failing tests:\n\ntest at test\\parallel\\test-async-context-frame.mjs:49:5\n✖ async-hooks\\test-async-local-storage-enter-with.js (1634.0662ms)\n  AssertionError [ERR_ASSERTION]: Test async-hooks\\test-async-local-storage-enter-with.js failed with exit code 3221225477\n  \n  3221225477 !== 0\n  \n      at TestContext.<anonymous> (file:///C:/workspace/node-test-binary-windows-js-suites/node/test/parallel/test-async-context-frame.mjs:59:7)\n      at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n      at async Test.run (node:internal/test_runner/test:935:9)\n      at async Suite.processPendingSubtests (node:internal/test_runner/test:633:7) {\n    generatedMessage: false,\n    code: 'ERR_ASSERTION',\n    actual: 3221225477,\n    expected: 0,\n    operator: 'strictEqual'\n  }"},"time":32419.083,"fullname":"parallel/test-async-context-frame","closingTestPoint":false}}]}